# This file was generated by GoReleaser. DO NOT EDIT.
cask "aisle" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "d426094658ac58ac25d19f2ae8289bb49897d11f4b5d5f771f3e4cd1b862cdc9"
      url "https://github.com/mashkovd/aisle/releases/download/v#{version}/aisle_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "16da0f331dfcc6df8cd8ab109105d3f5e8b3339502e60ae3a61be660537a9f1d"
      url "https://github.com/mashkovd/aisle/releases/download/v#{version}/aisle_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d9d2ca29916c82318613e20152133565be9d58c12aea42ad26dffacc4a53dfde"
      url "https://github.com/mashkovd/aisle/releases/download/v#{version}/aisle_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "393fa31bee2bdd3b718275d58893a15df00773f4e5652a915cf2418da0f1c76d"
      url "https://github.com/mashkovd/aisle/releases/download/v#{version}/aisle_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aisle"
  desc "Cross-agent session navigator for Claude Code, Codex, Gemini CLI and Antigravity"
  homepage "https://github.com/mashkovd/aisle"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "aisle"
  bash_completion "completions/aisle.bash"
  fish_completion "completions/aisle.fish"
  zsh_completion "completions/aisle.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aisle"]
    end
  end

  # No zap stanza required
end
