# This file was generated by GoReleaser. DO NOT EDIT.
cask "aisle" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "b59a3a337a685b805e1e82a685d7374f5ed80f2f7c511497c9e085bf4d6d7173"
      url "https://github.com/mashkovd/aisle/releases/download/v#{version}/aisle_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7e5c5fe0e54270d23a6845b2346be1b4902240c3f44cf10184f731dcd79ebd09"
      url "https://github.com/mashkovd/aisle/releases/download/v#{version}/aisle_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "23d5369261d27884ef0438cf2181d84dd6fe4508ae41de5f6f1fb9f1029c8ee1"
      url "https://github.com/mashkovd/aisle/releases/download/v#{version}/aisle_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9d8e8241f212c8f57b932f44bac4491bd7ca622079619b159a528ede3fe539c9"
      url "https://github.com/mashkovd/aisle/releases/download/v#{version}/aisle_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aisle"
  desc "Cross-agent session navigator for Claude Code, Codex, Gemini CLI and Antigravity"
  homepage "https://github.com/mashkovd/aisle"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "aisle"
  bash_completion "completions/aisle.bash"
  fish_completion "completions/aisle.fish"
  zsh_completion "completions/aisle.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aisle"]
    end
  end

  # No zap stanza required
end
