# This file was generated by GoReleaser. DO NOT EDIT.
cask "aisle" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "7a452defde7674806576bd45c575cd020c926061b3d1245699f23899310abb24"
      url "https://github.com/mashkovd/aisle/releases/download/v#{version}/aisle_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d1fca8f800df672a9ec112a0331a3776cdfa078480b5a9feb79e211169a48309"
      url "https://github.com/mashkovd/aisle/releases/download/v#{version}/aisle_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3d078a28939f0329044c4ffffcd5ac84bb0ae3ffdd7ff0397f88391e29af182d"
      url "https://github.com/mashkovd/aisle/releases/download/v#{version}/aisle_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8747680620622038d26a6554d5ff0b6cb70bba8ef43a8c941f350869ea158ad2"
      url "https://github.com/mashkovd/aisle/releases/download/v#{version}/aisle_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aisle"
  desc "Cross-agent session navigator for Claude Code, Codex, Gemini CLI and Antigravity"
  homepage "https://github.com/mashkovd/aisle"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "aisle"
  bash_completion "completions/aisle.bash"
  fish_completion "completions/aisle.fish"
  zsh_completion "completions/aisle.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aisle"]
    end
  end

  # No zap stanza required
end
